"use client";

import { useRef, useState } from "react";

const FRAME_RATE = 29.97;

export default function VisionSimulator() {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [playing, setPlaying] = useState(true);
  const [frame, setFrame] = useState(0);

  const togglePlayback = async () => {
    const video = videoRef.current;
    if (!video) return;

    if (video.paused) {
      await video.play();
    } else {
      video.pause();
    }
  };

  return (
    <section className="visionLab shell" id="vision-lab" data-reveal>
      <div className="sectionHead visionLabHead">
        <p>Real model output</p>
        <span>YOLO11n · MULTI-OBJECT TRACKING</span>
      </div>

      <div className="visionConsole">
        <div className="consoleBar">
          <div className="consoleStatus">
            <i className={playing ? "live" : "paused"} />
            <span>{playing ? "Model output playing" : "Playback paused"}</span>
          </div>
          <div className="consoleModel"><span>PIPELINE</span><b>YOLO11n + BYTE TRACK</b></div>
          <button type="button" onClick={togglePlayback} aria-pressed={!playing}>
            {playing ? "Pause footage" : "Play footage"}
          </button>
        </div>

        <div className="visionStage">
          <video
            ref={videoRef}
            src="/traffic-yolo-demo.mp4"
            poster="/traffic-yolo-poster.jpg"
            autoPlay
            muted
            loop
            playsInline
            aria-label="Traffic video processed with YOLO11n and ByteTrack, with bounding boxes following cars, trucks, and motorcycles"
            onPlay={() => setPlaying(true)}
            onPause={() => setPlaying(false)}
            onTimeUpdate={(event) => setFrame(Math.floor(event.currentTarget.currentTime * FRAME_RATE))}
          />
          <div className="stageVignette" aria-hidden="true" />
          <div className="stageHud bottomRight"><span>PROCESSED FOOTAGE</span><b>FRAME {String(frame).padStart(4, "0")}</b></div>
        </div>

        <div className="telemetry">
          <div><span>Model</span><strong className="locked">YOLO11n</strong><i style={{ "--meter": ".86" } as React.CSSProperties} /></div>
          <div><span>Video rate</span><strong>29.97<small> FPS</small></strong><i style={{ "--meter": ".75" } as React.CSSProperties} /></div>
          <div><span>Detector classes</span><strong>04</strong><i style={{ "--meter": ".66" } as React.CSSProperties} /></div>
          <div><span>Tracker</span><strong className="locked">BYTE TRACK</strong><i style={{ "--meter": ".92" } as React.CSSProperties} /></div>
        </div>
      </div>

      <div className="visionCaption">
        <h2>Not a mockup. Actual model output.</h2>
        <div>
          <p>Every box and track ID in this moving clip was generated by YOLO11n inference with ByteTrack on the source video. The result is pre-rendered for fast, reliable playback in the browser.</p>
          <a className="footageCredit" href="https://www.pexels.com/video/traffic-on-highway-in-city-12240861/" target="_blank" rel="noreferrer">Source footage · João Pavese / Pexels</a>
        </div>
      </div>
    </section>
  );
}
